
project_id = "lhqwzirrqenvlsffpefk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lhqwzirrqenvlsffpefk.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://127.0.0.1:54321/auth/v1/callback"

[storage]
enabled = true
file_size_limit = "50MiB"
allowed_mime_types = ["image/png", "image/jpeg", "image/gif", "image/webp"]

[edge_runtime]
enabled = true
inspector_port = 8083

[functions.fact-check-ai]
verify_jwt = false

[functions.news-api]
verify_jwt = false

[functions.video-generate]
verify_jwt = false

[functions.video-webhook]
verify_jwt = false

[functions.script-enhance]
verify_jwt = false
