// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhqwzirrqenvlsffpefk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocXd6aXJycWVudmxzZmZwZWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDAzNDUsImV4cCI6MjA2MjcxNjM0NX0.5frhpcXPCpOwevfwroPgIYRT1TKl_G-QDckCmYHIgns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);